version: '3'

services:
      
  donateverse-zipkin:
    container_name: donateverse-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - custom-network

  donateverse-discovery-server:
    container_name: donateverse-discovery-server
    build: 
      context: ./donateverse-discovery-server/
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge