version: '3'

services:

  donateverse-mysql:
    container_name: donateverse-mysql
    build:
      context: ./mysql/
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    networks:
      - custom-network
    environment:
      - MYSQL_ROOT_PASSWORD=root

  donateverse-prometheus:
    container_name: donateverse-prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - donateverse-user
    - donateverse-transaction
    - donateverse-gateway

  donateverse-zipkin:
    container_name: donateverse-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - custom-network

  donateverse-discovery-server:
    container_name: donateverse-discovery-server
    build: 
      context: ./donateverse-discovery-server/
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - custom-network

  donateverse-user:
    container_name: donateverse-user
    build: 
      context: ./donateverse-user/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - custom-network
    depends_on:
      - donateverse-discovery-server
      - donateverse-mysql
      - donateverse-zipkin

  donateverse-transaction:
    container_name: donateverse-transaction
    build: 
      context: ./donateverse-transaction/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    networks:
      - custom-network
    depends_on:
      - donateverse-discovery-server
      - donateverse-mysql
      - donateverse-zipkin

  donateverse-gateway:
    container_name: donateverse-gateway
    build: 
      context: ./donateverse-gateway/
      dockerfile: ./Dockerfile
    ports:
      - "9091:9091"
    networks:
      - custom-network
    depends_on:
      - donateverse-user
      - donateverse-transaction

  donateverse-center:
    container_name: donateverse-center
    build: 
      context: ./donateverse-center/
      dockerfile: ./Dockerfile
    ports:
      - "3012:3012"
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge